### PR TITLE
Updated node to newest LTS, installed Yarn in the recommended way

### PR DESCRIPTION
**Pull request by liamness**
Not sure how to actually test this, mind. It builds locally!

---
This change is [Reviewable](https://reviewable.io/reviews/elder-hq/build-tools/1)

### CODE REVIEW

**Comment by liamness** [comment]
Hmm, this seems to suggest that the newer images have yarn already, I'll check that:

https://hub.docker.com/r/yarnpkg/node-yarn/

**Comment by liamness** [comment]
Yep still builds even if I don't actually install Yarn.

**Comment by liamness** [comment]
Would suggest we get rid of yarn because . Also t

**Comment by kristian-elder** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elder-hq/build-tools/1)*

**Comment by liamness** [comment]
*[docker-images/javascript-circle-image/Dockerfile, line 37 at r2](https://reviewable.io:443/reviews/elder-hq/build-tools/1#-L5hrxs9kSvmnOQAzOqt:-L5hrxsAJZelpW2b9-he:b1jwyl7) ([raw file](https://github.com/elder-hq/build-tools/blob/fbc53d572c30ccf81e357de7074539131d174ecc/docker-images/javascript-circle-image/Dockerfile#L37)):*
> ```Dockerfile
>   echo "Installing Global Build Tools" && \
>   npm install -g flow-bin@v0.63.1 && \
>   npm install -g gulp-cli@2.0.0
> ```

@kristian-elder Think it would make more sense to do

`yarn global add flow-bin@v0.63.1 gulp-cli@2.0.0`

If we are using yarn we should try to use it everywhere, just to keep our knowledge of it sharp, and not end up muddled between that and npm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elder-hq/build-tools/1)*

**Comment by kristian-elder** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-images/javascript-circle-image/Dockerfile, line 37 at r2](https://reviewable.io:443/reviews/elder-hq/build-tools/1#-L5hrxs9kSvmnOQAzOqt:-L6N7upomGGbMPE5OVPC:b90xf1h) ([raw file](https://github.com/elder-hq/build-tools/blob/fbc53d572c30ccf81e357de7074539131d174ecc/docker-images/javascript-circle-image/Dockerfile#L37)):*
<details><summary><i>Previously, liamness (Liam Duffy) wrote…</i></summary><blockquote>

@kristian-elder Think it would make more sense to do

`yarn global add flow-bin@v0.63.1 gulp-cli@2.0.0`

If we are using yarn we should try to use it everywhere, just to keep our knowledge of it sharp, and not end up muddled between that and npm.
</blockquote></details>

We can kill the flow one altogether - the package.json will have a local flow-bin, and we want to keep that one in sync with the version we use in circleci, so should never really use a global one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elder-hq/build-tools/1)*

**Pull request closed without merging**
